services:
  - type: web
    name: cyber-crime-portal-2
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        sync: false
