const express = require("express");
const { protect, adminOnly } = require("../middleware/authMiddleware");
const { validateComplaint, validateStatusUpdate, handleValidationErrors, evidenceRequired } = require("../validators/complaintValidator");
const {
  createComplaint, getUserComplaints, getAllComplaints,
  updateComplaintStatus, getDashboardStats, getAnalytics,
  generateAISafetyGuidance
} = require("../controllers/complaintController");

const upload = require("../middleware/uploadMiddleware");
const authorizeRoles = require("../middleware/authorizeRoles");
const Complaint = require("../models/Complaint");

const router = express.Router();

// ── USER ─────────────────────────────────────────────────
router.post("/", protect, upload.single("evidence"), evidenceRequired, validateComplaint, handleValidationErrors, createComplaint);
router.get("/my", protect, getUserComplaints);
router.post("/ai-safety-guidance", protect, generateAISafetyGuidance);




// ── ADMIN ─────────────────────────────────────────────────
router.get("/stats",     protect, authorizeRoles("admin", "superadmin"), getDashboardStats);
router.get("/analytics", protect, authorizeRoles("admin", "superadmin"), getAnalytics);
router.get("/",          protect, authorizeRoles("admin", "superadmin"), getAllComplaints);
router.put("/:id/status", protect, authorizeRoles("admin", "superadmin"), validateStatusUpdate, handleValidationErrors, updateComplaintStatus);

// ── EXPORT CSV (PREMIUM AI UPGRADE) ───────────────────────
router.get("/export/csv", protect, authorizeRoles("admin", "superadmin"), async (req, res, next) => {
  try {
    const { priority, status, search, sort = "-createdAt" } = req.query;
    
    // ── Apply same filters as the main list ──────────────────────────
    const filter = {};
    if (priority  && priority.trim())  filter.priority  = priority;
    if (status    && status.trim())    filter.status    = status;
    if (search    && search.trim())    filter.$or = [
      { caseId:      { $regex: search, $options: "i" } },
      { scamTarget:  { $regex: search, $options: "i" } },
      { title:       { $regex: search, $options: "i" } }
    ];

    const complaints = await Complaint.find(filter)
      .populate("user", "name email")
      .sort(sort);

    // ── Metadata Section ─────────────────────────────────────────────
    const totalRecords = complaints.length;
    const exportDate = new Date().toLocaleString("en-IN", { 
      day: "2-digit", month: "2-digit", year: "numeric", 
      hour: "2-digit", minute: "2-digit", second: "2-digit",
      hour12: true 
    });
    
    const appliedFilters = [
      priority ? `Priority: ${priority}` : "Priority: All",
      status ? `Status: ${status}` : "Status: All",
      search ? `Search: "${search}"` : "Search: None"
    ].join(" | ");
    
    const metadata = [
      ["Generated By", "CyberShield Superadmin"],
      ["Export Date", exportDate],
      ["Total Records", totalRecords],
      ["Applied Filters", appliedFilters],
      [] // Blank separator row
    ].map(row => row.map(val => `"${val}"`).join(",")).join("\r\n") + "\r\n";

    // ── Header Row ───────────────────────────────────────────────────
    const headers = [
      "Case ID", "Reporter Name", "Reporter Email", "Complaint Title", 
      "Crime Type", "Scam Type", "Priority", "Risk Score", 
      "AI Category", "AI Confidence", "AI Severity", "AI Trend Cluster", 
      "Status", "Location", "Date Filed", "AI Summary", "AI Keywords"
    ].map(h => `"${h}"`).join(",") + "\r\n";

    // ── Data Rows ────────────────────────────────────────────────────
    const rows = complaints.map(c => {
      // Date formatting dd-mm-yyyy
      const d = new Date(c.createdAt);
      const day = String(d.getDate()).padStart(2, "0");
      const month = String(d.getMonth() + 1).padStart(2, "0");
      const year = d.getFullYear();
      const dateFiled = `${day}-${month}-${year}`;

      const rowData = [
        c.caseId,
        c.user?.name || "Anonymous User",
        c.user?.email || "N/A",
        (c.title || "N/A").replace(/"/g, '""').replace(/\n/g, " "),
        c.crimeType || "Unclassified",
        c.scamType || "Not Available",
        c.priority || "Low",
        c.riskScore || 0,
        c.aiCategory || "Not Available",
        c.aiConfidence ? `${c.aiConfidence}%` : "Not Available",
        c.aiSeverity ? c.aiSeverity.toUpperCase() : "Not Available",
        c.aiTrendContribution || "Not Available",
        c.status || "Pending",
        c.location || "Unknown",
        dateFiled,
        (c.aiSummary || "Not Available").replace(/"/g, '""').replace(/\n/g, " "),
        Array.isArray(c.aiKeywords) && c.aiKeywords.length > 0 ? c.aiKeywords.join(", ") : "Not Available"
      ];
      return rowData.map(val => `"${val}"`).join(",");
    }).join("\r\n");

    const dateStr = new Date().toISOString().split("T")[0];
    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename=CyberShield_Complaints_${dateStr}.csv`);

    // Add UTF-8 BOM for Excel compatibility
    const BOM = "\uFEFF";
    res.status(200).send(BOM + metadata + headers + rows);
  } catch (error) {
    next(error);
  }
});

// ── DYNAMIC (must be last) ────────────────────────────────
router.get("/:id", protect, async (req, res, next) => {
  try {
    const complaint = await Complaint.findById(req.params.id);
    if (!complaint) return res.status(404).json({ message: "Complaint not found" });
    if (complaint.user.toString() !== req.user.id && req.user.role !== "admin" && req.user.role !== "superadmin")
      return res.status(403).json({ message: "Not authorized to view this report" });
    res.json(complaint);
  } catch (error) {
    next(error);
  }
});

module.exports = router;
